node_sets {
  key: "cnn_node"
  value {
    features {
      key: "index"
      value: {
        dtype: DT_INT64
      }
    }
    features {
      key: "activation"
      value: {
        dtype: DT_FLOAT
      }
    }
  }
}

edge_sets {
  key: "cnn_edge"
  value {
    source: "cnn_node"
    target: "cnn_node"
  
  }
}
